services: 
  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    container_name: llama-server
    environment:
      - LLAMA_ARG_MODEL=/models/${LLAMA_MODEL_FILE:-DeepSeek-Coder-V2-Lite-Instruct-Q4_K_M.gguf}
      - LLAMA_ARG_HOST=0.0.0.0
      - LLAMA_ARG_PORT=11435
      - LLAMA_ARG_N_GPU_LAYERS=35
      - LLAMA_ARG_NGL=1
    volumes:
      - ./models/.llama:/models
    ports:
      - "11435:11435"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./models/.ollama:/root/.ollama
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
    environment:
      - NVIDIA_VISIBLE_DEVICES=all

  open-webui:
    image: ghcr.io/open-webui/open-webui:cuda
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    volumes:
      - open-webui:/app/backend/data
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped

volumes:
  open-webui:

networks:
  openwebui_net:
    driver: bridge