# Qwen Churn Assistant Infrastructure - CPU Mode
# Specialized setup for churn analysis using Qwen2.5-Coder models (CPU-only)
# Optimized for systems without GPU acceleration

services:
  ollama-qwen:
    image: ollama/ollama:latest
    container_name: ollama-qwen-churn
    ports:
      - "11434:11434"
    volumes:
      - ./models/.ollama:/root/.ollama
      - ./workspace/churn_analysis:/data/datasets:ro  # Read-only access to datasets
    restart: unless-stopped
    # CPU-specific memory limits to prevent OOM issues
    mem_limit: 16g
    mem_reservation: 8g
    # CPU optimization: limit cores if needed to prevent system lockup
    # cpus: "8.0"  # Uncomment and adjust if you need to limit CPU cores
    environment:
      # CPU-specific optimizations for Ollama
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_FLASH_ATTENTION=false
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s  # Longer interval for CPU mode
      timeout: 15s   # Longer timeout for CPU mode
      retries: 10
      start_period: 60s  # Longer start period for CPU mode
  #   networks:
  #     - openwebui_net

  # open-webui-qwen:
  #   image: ghcr.io/open-webui/open-webui:main
  #   container_name: open-webui-qwen-churn
  #   ports:
  #     - "3000:8080"
  #   environment:
  #     - OLLAMA_BASE_URL=http://ollama-qwen:11434
  #     - WEBUI_NAME=Qwen Churn Assistant (CPU Mode)
  #     # User access configuration
  #     - DEFAULT_USER_ROLE=admin    # First user becomes admin (needed for file uploads & model management)
  #     - ENABLE_SIGNUP=true         # Allow account creation (required for first-time setup)
  #     # Feature enablement
  #     - ENABLE_MEMORY=true         # Enable conversation memory for business analysis context
  #     - ENABLE_TOOLS=true          # Enable file upload and analysis tools
  #     - TOOLS_FUNCTION_CALLING_ENABLED=true  # Allow AI to use tools for data analysis
  #     # CPU mode specific settings
  #     - ENABLE_RAG_HYBRID_SEARCH=false  # Disable resource-intensive features for CPU mode
  #   depends_on:
  #     ollama-qwen:
  #       condition: service_healthy
  #   volumes:
  #     - qwen-churn-webui:/app/backend/data
  #   restart: unless-stopped
  #   # Memory limits for WebUI in CPU mode
  #   mem_limit: 4g
  #   mem_reservation: 2g
  #   networks:
  #     - openwebui_net

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama-qwen:11434
    depends_on:
      - ollama-qwen
    volumes:
      - qwen-churn-webui:/app/backend/data
    restart: unless-stopped

volumes:
  qwen-churn-webui:
    name: qwen-churn-assistant-data

networks:
  openwebui_net:
    driver: bridge


