services: 
  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server
    container_name: llama-server
    environment:
      - LLAMA_ARG_MODEL=/models/${LLAMA_MODEL_FILE:-DeepSeek-Coder-V2-Lite-Instruct-Q2_K.gguf}
      - LLAMA_ARG_HOST=0.0.0.0
      - LLAMA_ARG_PORT=11435
      # CPU-only configuration - no GPU layers
      - LLAMA_ARG_N_GPU_LAYERS=0
      - LLAMA_ARG_THREADS=8
      - LLAMA_ARG_CTX_SIZE=4096
    volumes:
      - ./models:/models
    ports:
      - "11435:11435"
    restart: unless-stopped

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama-models/.ollama:/root/.ollama
    restart: unless-stopped
    # CPU-only - no GPU device mapping

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama
    volumes:
      - open-webui:/app/backend/data
    restart: unless-stopped

volumes:
  open-webui:

networks:
  openwebui_net:
    driver: bridge
