# Ollama Service - Base Configuration (CPU-optimized by default)
# Can be used independently or with other services
# Use docker-compose.gpu-override.yml for GPU acceleration
# Use script-specific overrides for specialized setups

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    ports:
      - "11434:11434"
    volumes:
      - ./.ollama:/root/.ollama
    restart: unless-stopped
    environment:
      # CPU-optimized defaults
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_MAX_LOADED_MODELS=1
      - OLLAMA_FLASH_ATTENTION=false
      # Standard timeouts (sufficient for normal use)
      - OLLAMA_REQUEST_TIMEOUT=120     # 2 minutes for normal requests
      - OLLAMA_KEEP_ALIVE=2m           # Keep models loaded briefly
      - OLLAMA_MAX_REQUEST_SIZE=10m    # 10MB limit for normal use
      - OLLAMA_LOAD_TIMEOUT=5m         # Standard model loading
    # Laptop-friendly memory limits (optimized for 16GB available memory)
    deploy:
      resources:
        limits:
          memory: 12g  # Conservative limit for 7B model on memory-constrained laptop
        reservations:
          memory: 8g   # Minimum needed for 7B model
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 30s  # Standard interval for laptop use
      timeout: 15s   # Standard timeout
      retries: 5
      start_period: 60s  # Normal startup time
    networks:
      - ai_network

volumes:
  ollama-data:

networks:
  ai_network:
    driver: bridge
    external: true
