# Qwen Churn Assistant Infrastructure
# Specialized setup for churn analysis using Qwen2.5-Coder models

services:
  ollama-qwen:
    image: ollama/ollama:latest
    container_name: ollama-qwen-churn
    ports:
      - "11434:11434"
    volumes:
      - ./models/.ollama:/root/.ollama
      - ./workspace/churn_analysis:/data/datasets:ro  # Read-only access to datasets
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "ollama", "list"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 30s

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_BASE_URL=http://ollama-qwen:11434
    depends_on:
      - ollama-qwen
    volumes:
      - qwen-churn-webui:/app/backend/data
    restart: unless-stopped

volumes:
  qwen-churn-webui:
    name: qwen-churn-assistant-data
