services: 
  llama-server:
    image: ghcr.io/ggml-org/llama.cpp:server-cuda
    container_name: llama-server
    environment:
      - LLAMA_ARG_MODEL=/models/deepseek-coder-6.7B-instruct.Q4_K_M.gguf
      - LLAMA_ARG_HOST=0.0.0.0
      - LLAMA_ARG_PORT=11435
      - LLAMA_ARG_N_GPU_LAYERS=35
      - LLAMA_ARG_NGL=1
      - LLAMA_ARG_CHAT_TEMPLATE=llama2
    volumes:
      - ./models:/models
    ports:
      - "11435:11435"
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    restart: unless-stopped

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "3000:8080"
    environment:
      - OLLAMA_HOST=http://llama-server:11435
    depends_on:
      - llama-server
    volumes:
      - open-webui:/app/backend/data

volumes:
  open-webui:

networks:
  openwebui_net:
    driver: bridge