# Generic Docker Compose Override Template
# This file serves as a template for creating project-specific overrides
# The OllamaCustomModel class will process this template and create
# project-specific override files automatically

services:
  ollama:
    container_name: ollama-PROJECT_NAME_PLACEHOLDER
    hostname: ollama-PROJECT_NAME_PLACEHOLDER
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
      # Add project-specific environment variables here
    volumes:
      - ./.ollama/PROJECT_NAME_PLACEHOLDER:/root/.ollama
    networks:
      - ai_network
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://localhost:11434/api/tags || curl -f http://localhost:11434/api/tags || exit 1"]
      interval: 60s
      timeout: 15s
      retries: 5
      start_period: 120s  # Give more time for Ollama to initialize on first startup

  open-webui:
    container_name: open-webui-PROJECT_NAME_PLACEHOLDER
    hostname: open-webui-PROJECT_NAME_PLACEHOLDER
    environment:
      - WEBUI_NAME=PROJECT_TITLE_PLACEHOLDER
      - OLLAMA_BASE_URL=http://ollama-PROJECT_NAME_PLACEHOLDER:11434
      - WEBUI_AUTH=False
      # Add project-specific WebUI settings here
    volumes:
      - ./.webui/PROJECT_NAME_PLACEHOLDER/data:/app/backend/data
      - ./.webui/PROJECT_NAME_PLACEHOLDER/workspace:/app/backend/workspace
    networks:
      - ai_network
    depends_on:
      ollama:
        condition: service_healthy

volumes:
  PROJECT_NAME_PLACEHOLDER-data:
    driver: local
  PROJECT_NAME_PLACEHOLDER-memory:
    driver: local  
  PROJECT_NAME_PLACEHOLDER-workspace:
    driver: local

networks:
  ai_network:
    external: true